### ISSUE TITLE
Possible to add swipe event?

### ISSUE THREAD

**Issue by smlombardi** [lemmon/Lemmon-Slider#5]
Even using jquery.touchSwipe?  Are there previous/next events I can hook into?

**Comment by lemmon** [comment]
There are 4 events attached to the slider object - `nextSlide`, `prevSlide`, `nextPage`, and `prevPage`.

You can access them by calling `$slider.trigger('nextSlide');`

**Comment by smlombardi** [comment]
Thanks.  I have an issue with the slider having a 2px gap at the right edge.  I racked it to here:

```
.lemmon-slider {
    overflow: hidden;
    width: 100%;
    position: relative;
    left: -2px;
    margin: 0 auto;
}
```

If I set it to 0 then I get the gap on the left.  I can set width to something like 100.25% I guess...

**Comment by santyas** [comment]
@lemmon Hello, Can I use $slider.trigger('nextSlide'); in another file? ex. index.php

**Comment by carasmo** [comment]
This works smoothly:

https://github.com/mattbryson/TouchSwipe-Jquery-Plugin

```
window.onload = function () {

$('#lemmon-slider').lemmonSlider({
    infinite: true,
    loop: true
});


if ("ontouchstart" in document.documentElement) {

    $("#lemmon-slider").swipe({
        swipeLeft: function (event, direction, distance, duration, fingerCount) {
            $('.controls .prev-page').click();
        },
        swipeRight: function (event, direction, distance, duration, fingerCount) {
            $('.controls .next-page').click();
        },
        threshold: 0
    });
  }


   }
```

**Comment by edwardhotchkiss** [comment]
Nice solution @carasmo :+1:

**Comment by b-d-m-p** [comment]
@carasmo Thank you!

**Comment by Muskos** [comment]
@carasmo thx great
